'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { Globe, Shield, Activity, Cpu, Play, Sparkles, ChevronRight } from 'lucide-react';

interface LandingPageProps {
  onStart: () => void;
  hasActiveSave?: boolean;
  onResume?: () => void;
}

export const LandingPage: React.FC<LandingPageProps> = ({ onStart, hasActiveSave = false, onResume }) => {
  return (
    <div className="relative min-h-screen w-full flex flex-col items-center justify-center overflow-hidden bg-grid-pattern selection:bg-cyan-500 selection:text-black">
      {/* Background glowing gradient spheres */}
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-cyan-500/10 rounded-full blur-[120px] pointer-events-none animate-pulse" />
      <div className="absolute bottom-10 left-10 w-[400px] h-[400px] bg-emerald-500/10 rounded-full blur-[100px] pointer-events-none" />
      <div className="absolute top-10 right-10 w-[400px] h-[400px] bg-violet-500/10 rounded-full blur-[100px] pointer-events-none" />

      {/* Decorative Radar / Geopolitical Ring Animation */}
      <div className="absolute inset-0 flex items-center justify-center pointer-events-none opacity-20">
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ duration: 60, repeat: Infinity, ease: 'linear' }}
          className="w-[700px] h-[700px] border border-cyan-500/30 rounded-full border-dashed"
        />
        <motion.div
          animate={{ rotate: -360 }}
          transition={{ duration: 40, repeat: Infinity, ease: 'linear' }}
          className="absolute w-[500px] h-[500px] border border-emerald-500/30 rounded-full border-dotted"
        />
        <div className="absolute w-[300px] h-[300px] border border-slate-700 rounded-full" />
      </div>

      {/* Top Header / Brand Badge */}
      <motion.div
        initial={{ opacity: 0, y: -20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8 }}
        className="absolute top-8 flex items-center gap-2 px-4 py-2 rounded-full glass-panel border border-cyan-500/30 text-xs text-cyan-400 font-mono tracking-widest uppercase shadow-[0_0_15px_rgba(6,182,212,0.2)]"
      >
        <Sparkles className="w-3.5 h-3.5 animate-spin" style={{ animationDuration: '6s' }} />
        <span>Next-Gen Strategic Command AI • Version 2026.1</span>
      </motion.div>

      {/* Main Content Card */}
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.8, delay: 0.1 }}
        className="relative z-10 max-w-4xl px-6 text-center flex flex-col items-center"
      >
        {/* Animated Globe Icon */}
        <motion.div
          animate={{ y: [0, -10, 0] }}
          transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
          className="mb-6 p-5 rounded-3xl glass-panel border border-cyan-500/40 shadow-[0_0_40px_rgba(6,182,212,0.25)] relative group"
        >
          <Globe className="w-16 h-16 text-cyan-400 animate-pulse" />
          <div className="absolute inset-0 rounded-3xl bg-cyan-400/10 blur-xl opacity-0 group-hover:opacity-100 transition-opacity" />
        </motion.div>

        {/* Project Title */}
        <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight mb-6 font-sans">
          <span className="text-white drop-shadow-[0_2px_10px_rgba(255,255,255,0.2)]">Geo</span>
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 via-emerald-400 to-teal-300 glow-text-cyan">
            Polis
          </span>
        </h1>

        <p className="text-xl md:text-2xl font-light text-slate-300 max-w-2xl mb-10 leading-relaxed tracking-wide">
          AI Geopolitical & Grand Strategy Simulator. Command any world nation as Head of State, navigate multi-variable policy trade-offs, and witness realistic global consequences generated by real-time AI.
        </p>

        {/* Feature Highlights Pills */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-12 w-full max-w-3xl">
          <div className="glass-panel px-4 py-3 rounded-xl flex items-center gap-2.5 text-left border border-slate-800">
            <Activity className="w-5 h-5 text-cyan-400 flex-shrink-0" />
            <div>
              <div className="text-xs font-semibold text-slate-200">Dynamic Economy</div>
              <div className="text-[10px] text-slate-400">GDP, Inflation & Debt</div>
            </div>
          </div>
          <div className="glass-panel px-4 py-3 rounded-xl flex items-center gap-2.5 text-left border border-slate-800">
            <Shield className="w-5 h-5 text-emerald-400 flex-shrink-0" />
            <div>
              <div className="text-xs font-semibold text-slate-200">Military Readiness</div>
              <div className="text-[10px] text-slate-400">Nuclear & Tech Tiers</div>
            </div>
          </div>
          <div className="glass-panel px-4 py-3 rounded-xl flex items-center gap-2.5 text-left border border-slate-800">
            <Globe className="w-5 h-5 text-violet-400 flex-shrink-0" />
            <div>
              <div className="text-xs font-semibold text-slate-200">Global Diplomacy</div>
              <div className="text-[10px] text-slate-400">Alliances & Sanctions</div>
            </div>
          </div>
          <div className="glass-panel px-4 py-3 rounded-xl flex items-center gap-2.5 text-left border border-slate-800">
            <Cpu className="w-5 h-5 text-amber-400 flex-shrink-0" />
            <div>
              <div className="text-xs font-semibold text-slate-200">Groq AI Engine</div>
              <div className="text-[10px] text-slate-400">Real-time Consequences</div>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 w-full max-w-lg">
          {hasActiveSave && onResume && (
            <motion.button
              whileHover={{ scale: 1.04 }}
              whileTap={{ scale: 0.98 }}
              onClick={onResume}
              className="w-full sm:w-auto px-8 py-4 rounded-2xl bg-slate-900/80 hover:bg-slate-850 border border-cyan-500/50 text-cyan-400 font-bold text-lg flex items-center justify-center gap-2 shadow-[0_0_20px_rgba(6,182,212,0.15)] transition-all group"
            >
              <Sparkles className="w-5 h-5 text-cyan-400" />
              <span>Resume Active Session</span>
            </motion.button>
          )}

          <motion.button
            whileHover={{ scale: 1.04 }}
            whileTap={{ scale: 0.98 }}
            onClick={onStart}
            className={`${
              hasActiveSave ? 'w-full sm:w-auto' : 'w-full max-w-xs'
            } px-8 py-4 rounded-2xl bg-gradient-to-r from-cyan-500 to-emerald-500 hover:from-cyan-400 hover:to-emerald-400 text-black font-bold text-lg flex items-center justify-center gap-3 shadow-[0_0_25px_rgba(6,182,212,0.4)] transition-all group`}
          >
            <Play className="w-5 h-5 fill-black group-hover:translate-x-0.5 transition-transform" />
            <span>{hasActiveSave ? 'New Simulation' : 'Start Simulation'}</span>
            <ChevronRight className="w-5 h-5 opacity-70 group-hover:translate-x-1 transition-transform" />
          </motion.button>
        </div>
      </motion.div>

      {/* Footer System Diagnostics */}
      <div className="absolute bottom-6 flex items-center gap-6 text-[11px] font-mono text-slate-500">
        <span className="flex items-center gap-1.5">
          <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
          GROQ AI NEURAL LINK: ACTIVE
        </span>
        <span className="hidden md:inline">|</span>
        <span className="hidden md:inline">SESSION ENGINE: ACTIVE</span>
        <span className="hidden md:inline">|</span>
        <span className="hidden md:inline">SIMULATION SPEED: QUARTERLY</span>
      </div>
    </div>
  );
};
